export const SET_PROJECT_LIST = 'SET_PROJECT_LIST'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

export const SET_USER_SEX = 'SET_USER_SEX'

export const SET_SHELFBOOK_LIST = 'SET_SHELFBOOK_LIST'

export const SET_CUR_BOOK = 'SET_CUR_BOOK'

export const ADD_TO_SHELF = 'ADD_TO_SHELF'

export const SHELF_BOOK_UPDATE = 'SHELF_BOOK_UPDATE'
